- name: Mika Warm White
  entities:
    light.shelly_rgbw_ff_mika_led_strip:
      state: on
      brightness: 255
      white: 128
      rgb_color:
        - 0
        - 0
        - 0
    light.mika_bunt:
      state: on
      brightness: 64
      rgb_color:
        - 255
        - 182
        - 109