- name: Mika Chill
  entities:
    switch.ff_mika_bed: on
    switch.ff_mika_outlet: on
    light.mika_bunt:
      state: on
      brightness_pct: 25
      rgb_color:
        - 255
        - 182
        - 109