- platform: darksky
  api_key: !secret darksky_api_key
  language: de
  monitored_conditions:
    - summary
    - daily_summary
    - temperature
    - apparent_temperature
    - wind_speed
    - cloud_cover
    - visibility
    - humidity
    - pressure
    - temperature_high
    - temperature_low