
- platform: template
  sensors:
    mirko:
      value_template: '{{ states.group.mirko.state }}'
      friendly_name: 'Mirko'

- platform: template
  sensors:
    femke:
      value_template: '{{ states.group.femke.state }}'
      friendly_name: 'Femke'

- platform: template
  sensors:
    mika:
      value_template: '{{ states.group.mika.state }}'
      friendly_name: 'Mika'