- platform: time_date
  display_options:
    - "date"
    - "time"

- platform: template
  sensors:
    weekofyear:
      friendly_name: 'Kalenderwoche'
      value_template: "{{ now().strftime('%U') }}"