mirko_state:
    name: Mirko
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

femke_state:
  name: Femke
  options:
    - Home
    - Just Arrived
    - Just Left
    - Away
    - Extended Away
  initial: Home
  
mika_state:
  name: Mika
  options:
    - Home
    - Just Arrived
    - Just Left
    - Away
    - Extended Away
  initial: Home