# ####################################################
# Morning routine
# ####################################################
- alias: "Turn on kids light in the morning"
  trigger:
    platform: time
    at: '06:30:00'  
  condition:        
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: group.ff_children
   

- alias: "Turn off bed in the morning"
  trigger:
    platform: time
    at: '07:15:00'  
  condition:        
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.ff_children
    

# ####################################################
# Evening routines
# ####################################################

- alias: "Turn on lights: Floor"
  trigger: 
    platform: state
    entity_id: input_boolean.sunset
    to: 'on'
  action:
    - service: light.turn_on
      data:
        brightness_pct: 40
        entity_id:
          - light.meq0397149
    - service: switch.turn_on
      entity_id: switch.ff_floor_tree
    - delay: "00:00:05"
    - service: switch.turn_on
      entity_id: switch.ff_floor_tree
    - service: switch.turn_on
      entity_id: group.ff_children
    - delay: "00:00:05"
    - service: switch.turn_on
      entity_id: group.ff_children
          

- alias: "Turn off lights: Floor"
  trigger:    
    platform: time
    at: '22:30:00'
  action:
    - service: homeassistant.turn_off
      entity_id: group.ff_floor_lights
    - delay: "00:00:05"
    - service: switch.turn_off
      entity_id: switch.ff_floor_tree
    - delay: "00:00:05"
    - service: switch.turn_off
      entity_id: switch.ff_floor_tree


- alias: "Turn off lights: children k1"
  trigger:    
    platform: time
    at: '21:00:00'  
  action:
    - service: switch.turn_off
      entity_id: switch.ff_mika_bed
    - delay: "00:00:05"
    - service: switch.turn_off
      entity_id: switch.ff_mika_bed
    - delay: "00:00:05"
    - service: switch.turn_off
      entity_id: switch.ff_mika_bed


- alias: "Turn off lights: children k2"
  trigger:    
    platform: time
    at: '20:30:00'  
  action:
    - service: switch.turn_off
      entity_id: switch.ff_jona_bed
    - delay: "00:00:05"
    - service: switch.turn_off
      entity_id: switch.ff_jona_bed
    - delay: "00:00:05"
    - service: switch.turn_off
      entity_id: switch.ff_jona_bed