- alias: SF No Presence
  trigger:
    - platform: state
      entity_id: sensor.bt_mirko_room_presence      
      from: 'second_floor' # SF
      to: 'groundfloor' # GF
  condition:  
    condition: and
    conditions:
      - condition: state
        entity_id: group.second_floor_lights
        state: 'on'
  action:
    - data:
        data:
          actions:
          - action: room_presence_turn_lights_sf_off
            title: Turn SF lights off
        message: "Keiner mehr im Obergeschoss"
        title: '*Home-Assistant*'
      service: notify.mobile_app_galaxy_s10


- alias: SF No Presence Action
  trigger:
    - event_data:
        action: room_presence_turn_lights_sf_off
      event_type: mobile_app_notification_action
      platform: event
  action:
    - data:
        entity_id: group.second_floor_lights
      service: homeassistant.turn_off
    - service: notify.mobile_app_galaxy_s10
      data:
        title: '*Home-Assistant*'
        message: "Turned off SF lights"


- alias: SF Presence
  trigger:
    - platform: state
      entity_id: sensor.bt_mirko_room_presence      
      from: 'groundfloor' # GF
      to: 'second_floor' # SF
  condition:  
    condition: and
    conditions:
      - condition: state
        entity_id: group.second_floor_lights
        state: 'off'
      - condition: state
        entity_id: input_boolean.sunset
        state: 'on'
  action:
    - data:
        data:
          actions:
          - action: room_presence_turn_lights_sf_on
            title: Turn SF lights on
        message: "Keiner Licht im Obergeschoss. Anmachen?"
        title: '*Home-Assistant*'
      service: notify.mobile_app_galaxy_s10


- alias: SF Presence Action
  trigger:
    - event_data:
        action: room_presence_turn_lights_sf_on
      event_type: mobile_app_notification_action
      platform: event
  action:
    - data:
        entity_id: group.second_floor_lights
      service: homeassistant.turn_on
    - service: notify.mobile_app_galaxy_s10
      data:
        title: '*Home-Assistant*'
        message: "Turned on SF lights"
