- alias: "Turn on: Sunset Event"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
    # - platform: time
    #   at: '15:32:00'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.sunset


- alias: "Turn on: Sunrise Event"
  trigger:
    platform: sun
    event: sunrise   
    offset: "+01:00:00"
  # condition:
  #   - condition: sun
  #     after: sunrise
  #   - condition: time
  #     after: '06:30:00'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.sunset
