- alias: "System Startup"
  trigger:
    platform: homeassistant
    # Event can also be 'shutdown'
    event: start
  action:
    service: notify.telegram
    data:
      title: "HA - System"
      message: "Homeassistant ist gestartet"


- alias: Alexa Media Player Authentication Required
  trigger:
    platform: event
    event_type: alexa_media_relogin_required
  condition: []
  action:
  - service: notify.mobile_app_galaxy_s10
    data:
      title: Alexa Media Player Integration
      message: 🔑 Authentication Required
      data:
        actions:
        - action: URI
          title: Resolve now!
          uri: /lovelace/home