- alias: "TESTI"
  trigger:    

  action:    
    - service: notify.telegram
      data:
        title: '*Send a message*'
        message: "That's an example that _sends_ a *formatted* message with a custom inline keyboard."
        data:
          inline_keyboard:
            - 'Task 1:/command1, Task 2:/command2'
            - 'Task 3:/command3, Task 4:/command4'
