dsl:
  name: DSL
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.net_rate_down_max
    - sensor.net_rate_up_max
  hours_to_show: 96
  refresh: 600
  
temperatur:
  name: Temperatur
  entities:
    - sensor.luftdaten_temperature
    - sensor.aeotec_zw100_multisensor_6_temperature
  hours_to_show: 72
  refresh: 600

bt_presence:
  name: BT Presence
  entities:
    - sensor.bt_presence_ff_family
    - sensor.bt_presence_ff_mirko_iphone
    - sensor.bt_presence_ff_femke_iphone
    - sensor.bt_presence_ff_mika_huawei
  hours_to_show: 72
  refresh: 600
