dsl:
  name: DSL
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
  hours_to_show: 96
  refresh: 600
  
temperatur:
  name: Temperatur
  entities:
    - sensor.luftdaten_14343_temperature
    - sensor.aeotec_zw100_multisensor_6_temperature
  hours_to_show: 72
  refresh: 600

bt_presence:
  name: BT Presence
  entities:
    - sensor.bt_presence_ff_family
  hours_to_show: 6
  refresh: 120
