default: error
logs:
  homeassistant.components.media_player: warning

# default: info
# logs:
#   aiohttp.client_exceptions: critical
#   aiohttp.access: critical
#   aiohttp.server: critical
#   googleapiclient.discovery: error
#   pyhomematic.devicetypes.generic: error
#   homeassistant.core: error
#   homeassistant.components.automation: warn
#   homeassistant.components.binary_sensor: error
#   homeassistant.components.climate.nest: warn
#   homeassistant.components.device_tracker: error
#   homeassistant.components.discovery: warn
#   homeassistant.components.feedreader: warn
#   homeassistant.components.http: warn
#   homeassistant.components.media_player: critical  
#   homeassistant.components.sensor.rest: critical
#   homeassistant.components.recorder: error
#   homeassistant.components.sensor.darksky: warn
#   homeassistant.components.zwave: warn
#   homeassistant.helpers.script: info
#   homeassistant.helpers.entity: critical
#   homeassistant.exceptions: info
#   py.warnings: error
#   requests.packages.urllib3.connectionpool: critical  
#   root: warn