purge_interval: 1
purge_keep_days: 30
# include:
#   entities:
#     - group.landscaping
exclude:
  domains:
    - updater
    - automation
    - device_tracker
    - group
    - scene
    - script
  entities:    
    - sensor.date    
    - sun.sun
    - zone.home