stadtreinigung:
  name: Stadtreinigung
  entities:
    - binary_sensor.srhh_morgen_blau
    - binary_sensor.srhh_morgen_gelb
    - binary_sensor.srhh_morgen_gruen
    - binary_sensor.srhh_morgen_schwarz