stadtreinigung:
  name: Stadtreinigung
  entities:
    - binary_sensor.srhh_morgen_blue
    - binary_sensor.srhh_morgen_green
    - binary_sensor.srhh_morgen_yellow
    - binary_sensor.srhh_morgen_black