title: EG
id: groundfloor
background: var(--background-image)
cards:
  - type: "custom:config-template-card"
    entities:
      - group.kitchen
      - group.livingroom
      - group.garden_lights
    card:
      type: 'custom:hui-glance-card'
      entities:
        - entity: group.kitchen
          hold_action:
              action: toggle
          icon: "${states['group.kitchen'].state === 'on' ? 'mdi:coffee' : 'mdi:coffee-outline' }"
        - entity: group.livingroom
          hold_action:
              action: toggle
          icon: "${states['group.livingroom'].state === 'on' ? 'mdi:seat' : 'mdi:seat-outline' }"
        - entity: group.garden_lights
          hold_action:
              action: toggle
          icon: "${states['group.garden_lights'].state === 'on' ? 'mdi:flower' : 'mdi:flower-outline' }"
  - type: custom:auto-entities
    id: overview_scenes
    filter:
      include:
        - group: group.scenes
    card:
      type: entities
      title: Szenen
      show_header_toggle: false
  - type: custom:auto-entities
    id: gf_entrence_lights
    filter:
      include:
        - group: group.entree_lights
    card:
      type: entities
      title: Eingangsbereich
  - type: custom:auto-entities
    id: gf_kitchen_entities
    filter:
      include:
        - group: group.kitchen_lights
    card:
      type: entities
      title: "K\xFCche Lichter"
  - type: custom:auto-entities
    id: gf_living_room_lights
    filter:
      include:
        - group: group.livingroom_lights
    card:
      type: entities
      title: Wohnzimmer Lichter
  - type: custom:auto-entities
    id: gf_garden_lights
    filter:
      include:
        - group: group.garden_lights
    card:
      type: entities
      title: Garten
  - type: custom:auto-entities
    id: gf_wardrobe_entities
    filter:
      include:
        - group: group.wardrobe_lights
    card:
      type: entities
      title: "Garderobe Lichter"
  - type: custom:mini-media-player
    id: gf_media_control_rxv_zone1
    artwork: cover
    icon: mdi:headphones
    entity: media_player.yamaha_receiver
  # - type: media-control
  #   id: gf_media_control_rxv_zone1
  #   entity: media_player.yamaha_receiver
  - type: custom:mini-media-player
    id: gf_media_control_rxv_zone2
    artwork: cover
    icon: mdi:speaker
    entity: media_player.yamaha_receiver_zone_2
  - type: custom:mini-media-player
    id: gf_media_control_panasonic
    icon: mdi:television
    entity: media_player.panasonic_viera_tv