title: EG
id: groundfloor
background: var(--background-image)
cards:
  - type: "custom:config-template-card"
    entities:
      - group.kitchen
      - group.livingroom
      - group.garden_lights
    card:
      type: 'custom:hui-glance-card'
      entities:
        - entity: group.kitchen
          hold_action:
              action: toggle
          icon: "${states['group.kitchen'].state === 'on' ? 'mdi:coffee' : 'mdi:coffee-outline' }"
        - entity: group.livingroom
          hold_action:
              action: toggle
          icon: "${states['group.livingroom'].state === 'on' ? 'mdi:seat' : 'mdi:seat-outline' }"
        - entity: group.garden_lights
          hold_action:
              action: toggle
          icon: "${states['group.garden_lights'].state === 'on' ? 'mdi:flower' : 'mdi:flower-outline' }"

  - type: entities
    title: Küche
    show_header_toggle: true
    entities:
      - entity: light.homegear_eg_table
      - entity: light.homegear_eg_sink
      - entity: switch.gf_kitchen_window
      - entity: switch.gf_kitchen_workplace
      # - entity: switch.gf_free_outlet_2
      - entity: media_player.yamaha_receiver_zone_2
        type: custom:mini-media-player
        artwork: cover
        icon: mdi:speaker
        name: Receiver Küche      

  - type: entities
    title: Wohnzimmer
    show_header_toggle: true
    entities:
      - entity: group.livingroom_couch
      - entity: light.links
      - entity: light.rechts
      - entity: switch.gf_livingroom_outlet 
      - entity: light.homegear_eg_living_room
      - entity: media_player.yamaha_receiver
        type: custom:mini-media-player
        artwork: material
        idle_view: when_idle
        icon: mdi:speaker
        name: Receiver
      - entity: media_player.viera_gt30_series_2
        type: custom:mini-media-player
        icon: mdi:television
        name: Fernseher

  - type: custom:auto-entities
    id: gf_entrence_lights
    filter:
      include:
        - group: group.entree_lights
    card:
      type: entities
      title: Eingangsbereich

  - type: custom:auto-entities
    id: gf_garden_lights
    filter:
      include:
        - group: group.garden_lights
    card:
      type: entities
      title: Garten

  - type: custom:auto-entities
    id: gf_wardrobe_entities
    filter:
      include:
        - group: group.wardrobe_lights
    card:
      type: entities
      title: "Garderobe Lichter"

  

  - type: custom:auto-entities
    id: overview_scenes
    filter:
      include:
        - group: group.scenes
    card:
      type: entities
      title: Szenen
      show_header_toggle: false