title: DG
id: secondfloor
background: var(--background-image)
cards:
  - type: glance
    id: sf_glance
    entities:
      - entity: group.sf_work_lights
        hold_action:
            action: toggle
        icon: mdi:monitor-cellphone-star
      - entity: group.sf_bedroom_lights
        hold_action:
            action: toggle
        icon: mdi:bed-outline
  - type: entities
    title: Arbeitszimmer
    show_header_toggle: false
    entities:
      - switch.sf_floor_work_desk
      - switch.sf_floor_work_outlet
      - switch.sf_floor_work_shelf
      - entity: media_player.echo_dg_arbeitszimmer
        type: custom:mini-media-player    
        artwork: cover
        icon: mdi:headphones      
        name: Alexa
  - type: entities
    title: Schlafzimmer
    show_header_toggle: false
    entities:
      - switch.sf_bedroom_outlet
      - switch.sf_bedroom_bed
      - entity: media_player.echo_dg_schlafzimmer
        type: custom:mini-media-player    
        artwork: cover
        icon: mdi:headphones      
        name: Alexa
