title: System
id: system
icon: mdi:cogs
background: var(--background-image)
cards:
  - type: horizontal-stack
    title: Speedtest
    cards:
    - color_thresholds_transition: smooth
      entities:
      - entity: sensor.speedtest_ping
        index: 0
        name: Ping
      font_size: 70
      group: false
      hour24: true
      line_width: 6
      lower_bound: 0
      points_per_hour: 1
      show:
        extrema: true
        fill: fade
        icon: true
        labels: false
        name: true
        state: true
      type: custom:mini-graph-card
    - color_thresholds_transition: smooth
      entities:
      - entity: sensor.speedtest_download
        index: 0
        name: Download
      font_size: 70
      group: false
      hour24: true
      line_width: 6
      lower_bound: 0
      points_per_hour: 1
      show:
        extrema: true
        fill: fade
        icon: true
        labels: false
        name: true
        state: true
      type: custom:mini-graph-card
    - color_thresholds_transition: smooth
      entities:
      - entity: sensor.speedtest_upload
        index: 0
        name: Upload
      font_size: 70
      group: false
      hour24: true
      line_width: 6
      lower_bound: 0
      points_per_hour: 1
      show:
        extrema: true
        fill: fade
        icon: true
        labels: false
        name: true
        state: true
      type: custom:mini-graph-card

  - type: horizontal-stack
    title: Pi Hole
    id: system_sensor_pihole
    cards:
      - type: sensor
        id: system_sensor_pi_hole_ads_percentage_blocked_today
        entity: sensor.pi_hole_ads_percentage_blocked_today
        name: "% Ads blocked"
        graph: line
      - type: sensor
        id: system_sensor_pi_hole_dns_queries_today
        entity: sensor.pi_hole_dns_queries_today
        name: DNS queries
        graph: line

  - type: horizontal-stack
    id: system_raspberry
    title: Raspberry Health
    cards:
      - type: custom:mini-graph-card
        color_thresholds_transition: smooth
        entities:
        - entity: sensor.load_5m
          index: 0
          name: Load 5m
        font_size: 70
        group: false
        hour24: true
        line_width: 6
        lower_bound: 0
        points_per_hour: 1
        show:
          extrema: true
          fill: fade
          icon: true
          labels: false
          name: true
          state: true
      - type: custom:mini-graph-card
        color_thresholds_transition: smooth
        entities:
        - entity: sensor.disk_use_percent_home
          index: 0
          name: Disk Use (%)
        font_size: 70
        group: false
        hour24: true
        line_width: 6
        lower_bound: 0
        points_per_hour: 1
        show:
          extrema: true
          fill: fade
          icon: true
          labels: false
          name: true
          state: true
      - type: custom:mini-graph-card
        color_thresholds_transition: smooth
        entities:
        - entity: sensor.memory_use_percent
          index: 0
          name: Memory Use (%)
        font_size: 70
        group: false
        hour24: true
        line_width: 6
        lower_bound: 0
        points_per_hour: 1
        show:
          extrema: true
          fill: fade
          icon: true
          labels: false
          name: true
          state: true

  - type: horizontal-stack
    id: system_raspberry
    title: Batterien
    cards:
    - type: sensor
      id: system_sensor_tradfri_wireless_dimmer
      entity: sensor.tradfri_wireless_dimmer
      name: Wireless Dimmer
      graph: line
    - type: sensor
      id: system_sensor_tradfri_motion_sensor
      entity: sensor.tradfri_motion_sensor
      name: Motion Sensor
      graph: line
