# - platform: mqtt
#   schema: template
#   name:  shelly_dim_eg_bicycles
#   state_topic: "shellies/shellydimmer-DB4A90/light/0/status"
#   state_value_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
#   command_topic: "shellies/shellydimmer-DB4A90/light/0/set"
#   command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
#   command_off_template: '{"turn": "off"}'
#   brightness_value_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'


- platform: mqtt
  schema: template
  name: 'shelly_dim_eg_bicycles'
  command_topic: "shellies/shellydimmer-DB4A90/light/0/set" 
  state_topic: "shellies/shellydimmer-DB4A90/light/0/status"
  state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
  command_off_template: '{"turn":"off"}'
  command_on_template: >
      {"turn": "on"
      {%- if brightness is defined -%}
      , "brightness": {{brightness | float | multiply(0.3882 + 1) | round(0)}}
      {%- endif -%}
      }
  brightness_template: "{{ value_json.brightness | float | multiply(2.55) | round(0) }}"
  qos: 1