- platform: template
  sensors:
    srhh_morgen_blue:
      friendly_name: "Blaue Papiertonne (morgen)"
      value_template: >-
        {% set collection = as_timestamp(states.sensor.stadtreinigung_hamburg_home_blaue_papiertonne.state)|timestamp_custom("%Y-%m-%d") %}
        {% set tomorrow = (as_timestamp(now()) + 86400)|timestamp_custom("%Y-%m-%d") %}
        {{ collection == tomorrow }}
    srhh_morgen_green:
      friendly_name: "Grüne Biotonne (morgen)"
      value_template: >-
        {% set collection = as_timestamp(states.sensor.stadtreinigung_hamburg_home_grune_biotonne.state)|timestamp_custom("%Y-%m-%d") %}
        {% set tomorrow = (as_timestamp(now()) + 86400)|timestamp_custom("%Y-%m-%d") %}
        {{ collection == tomorrow }}
    srhh_morgen_yellow:
      friendly_name: "Gelbe Wertstofftonne (morgen)"
      value_template: >-
        {% set collection = as_timestamp(states.sensor.stadtreinigung_hamburg_home_gelbe_wertstofftonne_sack.state)|timestamp_custom("%Y-%m-%d") %}
        {% set tomorrow = (as_timestamp(now()) + 86400)|timestamp_custom("%Y-%m-%d") %}
        {{ collection == tomorrow }}
    srhh_morgen_black:
      friendly_name: "Schwarze Restmülltonne (morgen)"
      value_template: >-
        {% set collection = as_timestamp(states.sensor.stadtreinigung_hamburg_home_schwarze_restmulltonne.state)|timestamp_custom("%Y-%m-%d") %}
        {% set tomorrow = (as_timestamp(now()) + 86400)|timestamp_custom("%Y-%m-%d") %}
        {{ collection == tomorrow }}