alias: Alarm Clock
sequence:
  - service: light.turn_on
    data_template:
      entity_id:
        - "switch.ff_{{name}}_bed"
        - "switch.ff_{{name}}_outlet"

  - service: light.turn_on
    data_template:
      entity_id: "light.{{name}}_bunt"
      brightness: 10
      rgb_color:
        - 255
        - 0
        - 0

  - delay: "00:02:00"

  - service: light.turn_on
    data_template:
      entity_id: "light.{{name}}_bunt"
      brightness: 20
      rgb_color:
        - 255
        - 77
        - 0

  - delay: "00:02:00"

  - service: light.turn_on
    data_template:
      entity_id: "light.{{name}}_bunt"
      brightness: 40
      rgb_color:
        - 255
        - 103
        - 0

  - delay: "00:02:00"

  - service: light.turn_on
    data_template:
      entity_id: "light.{{name}}_bunt"
      brightness: 60
      rgb_color:
        - 255
        - 129
        - 0

  - delay: "00:02:00"

  - service: light.turn_on
    data_template:
      entity_id: "light.{{name}}_bunt"
      brightness: 80
      rgb_color:
        - 255
        - 167
        - 0

  - delay: "00:02:00"

  - service: light.turn_on
    data_template:
      entity_id: "light.{{name}}_bunt"
      brightness: 100
      rgb_color:
        - 255
        - 167
        - 0