alias: Mika Night Mode
sequence:
  - service: light.turn_on
    data:
      entity_id: light.shelly_rgbw_ff_mika_led_strip
      rgb_color: [255,0,0]
      brightness: 15
      white_value: 0
  - service: light.turn_on
    data:
      entity_id: light.mika_bunt
      brightness: 25
      rgb_color: [255,0,0]