alias: TV Scene
sequence:
  - service: media_player.turn_on
    data:
      entity_id: media_player.yamaha_receiver
  - service: media_player.volume_set
    data:
      entity_id: media_player.yamaha_receiver
      volume_level: 0.55
  - service: media_player.select_source
    data:
      entity_id: media_player.yamaha_receiver
      source: AV1
      